-- Generated by web/tools/gen_games_sql.py from data/issue.json. Do not edit by hand.
insert into public.games (slug, title, genres, reviewable, opens_on) values
  ('runescape-dragonwilds', 'RuneScape: Dragonwilds', array['survival','co-op','rpg','adventure']::text[], true, '2026-09-15'),
  ('marvel-cosmic-invasion', 'Marvel Cosmic Invasion', array['action','beat-em-up','co-op']::text[], false, '2026-09-16'),
  ('planet-of-lana-ii', 'Planet of Lana II', array['adventure','puzzle','platformer']::text[], false, '2026-09-16'),
  ('routine', 'Routine', array['horror','adventure']::text[], false, '2026-09-16'),
  ('ultimate-sheep-raccoon', 'Ultimate Sheep Raccoon', array['party','co-op']::text[], false, '2026-09-16'),
  ('kernel-hearts', 'Kernel Hearts', array['action','rpg','roguelite','co-op']::text[], true, '2026-09-17'),
  ('ninja-gaiden-4', 'Ninja Gaiden 4', array['action']::text[], true, '2026-09-17'),
  ('dune-awakening', 'Dune: Awakening', array['survival','rpg','adventure','co-op']::text[], true, '2026-09-22'),
  ('well-dweller', 'Well Dweller', array['metroidvania','action','adventure','platformer']::text[], true, '2026-09-22'),
  ('mad-king-redemption', 'Mad King Redemption', array['beat-em-up','roguelite','action','co-op','early-access']::text[], true, '2026-09-23'),
  ('call-of-duty-black-ops-6', 'Call of Duty: Black Ops 6', array['shooter','action']::text[], false, '2026-09-25'),
  ('rematch', 'Rematch', array['sports']::text[], false, '2026-09-25'),
  ('minecraft-dungeons-ii', 'Minecraft Dungeons II', array['action','rpg','co-op','adventure']::text[], true, '2026-09-29'),
  ('keeper', 'Keeper', array['puzzle','adventure']::text[], true, '2025-10-17'),
  ('gears-of-war-e-day', 'Gears of War: E-Day', array['shooter','action']::text[], false, '2026-10-06')
on conflict (slug) do update set title = excluded.title, genres = excluded.genres,
  reviewable = excluded.reviewable, opens_on = excluded.opens_on;
