#!/usr/bin/env python3
"""Generate the SQL that mirrors data/issue.json games into the Supabase `games` table.

Run after adding games/issues to data/issue.json:
    python tools/gen_games_sql.py > ../community/supabase/migrations/<timestamp>_games.sql
(or paste the output into the Supabase SQL editor). Idempotent upsert.
Games with a review page (`reviewed: true`) are open for player reviews from
`playerReviewsOpen` (if set) or their Game Pass date.
"""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
d = json.loads((root / 'data' / 'issue.json').read_text())
q = lambda s: "'" + str(s).replace("'", "''") + "'"
rows = []
for g in d['games']:
    genres = 'array[' + ','.join(q(x) for x in g['genres']) + ']::text[]'
    rows.append(f"  ({q(g['slug'])}, {q(g['title'])}, {genres}, {'true' if g.get('reviewed') else 'false'}, {q(g.get('playerReviewsOpen', g['date']))})")
print('-- Generated by web/tools/gen_games_sql.py from data/issue.json. Do not edit by hand.')
print('insert into public.games (slug, title, genres, reviewable, opens_on) values')
print(',\n'.join(rows))
print('on conflict (slug) do update set title = excluded.title, genres = excluded.genres,')
print('  reviewable = excluded.reviewable, opens_on = excluded.opens_on;')
